### PR TITLE
Protect the cadence mix-in from bogus data

### PR DESCRIPTION
**Pull request by tkordenbrock**
cadence_mixin.dart
* in addCadenceData(), add more protections from data that will disrupt the cadence smoothing
* ignore if the monotonically increasing revolutions counter went backwards
* ignore if the revolutions counter jumped forward by an unreasonable amount
* ignore if the revolutions counter didn't change but the time did
* in all cases, update the timestamp of the last record in the cadence queue

I'm not sure this is generally useful.  It may be specific to the Schwinn x70 bikes or even my bike.

### CODE REVIEW

**Comment by MrCsabaToth** [comment]
I'll be extremely careful for changes in this Mixin, because it affects CSC cadence sensors, speed sensors and power meters. I'll have to verify any change at least with my cadence and speed sensor setup.

1. If the monotonically increasing revolution counter goes backward theoretically that means that there was an overflow. The code does number of overflows and then account for that during calculations. Do you have any occasions where it is not an overflow?
2. I'd want to handle this jump forward for X70 specifically by possibly ignoring the bit which causes this. Can this happen that we think that somehow we end up treating this as an unsigned value and somehow after overflow it is signed and the bits causes this (or the other way around?).
3. If the revolution time didn't change but the time stamp did, then we need to update the entry in the queue with the newer time stamp. (?) Because the cadence is essentially the deltaRevolutions / deltaTime.

I'll need to have some free time and download these change and deep think.

**Comment by tkordenbrock** [comment]
>1. If the monotonically increasing revolution counter goes backward theoretically that means that there was an overflow.  The code does number of overflows and then account for that during calculations. Do you have any occasions where it is not an overflow?

I don't have any case where there was a negative `revDiff` that was not an overflow.  I was working from the idea that there could be random(?) bit flips in the 3rd byte.  That could give a negative `revDiff` but not be an overflow.  In the case of an overflow, the new rev count would be small (probably less than 20).  That fact could be incorporated into the condition.

>2. I'd want to handle this jump forward for X70 specifically by possibly ignoring the bit which causes this. Can this happen that we think that somehow we end up treating this as an unsigned value and somehow after overflow it is signed and the bits causes this (or the other way around?).

I couldn't identify a single bit (or even a few specific bits) that always changed.  After thinking about it for a while, I decided that the only reliable way to prevent the problem is to ignore the high 8 bits.  Then I was looking through some old debug logs looking for negative `revDiff` values and found this instead.

```
2024-03-10 07:16:03.450272,INFO,FITNESS_EQUIPMENT,_listenToData loop,key 8209 byteListPrep [17, 32, 0, 0, 253, 255, 0, 128, 62, 248, 192, 39, 86, 34, 0, 0, 6]
2024-03-10 07:16:04.237438,INFO,FITNESS_EQUIPMENT,_listenToData loop,key 8209 byteListPrep [17, 32, 0, 0, 254, 255, 0, 0, 100, 251, 0, 29, 89, 34, 0, 0, 6]
2024-03-10 07:16:05.047461,INFO,FITNESS_EQUIPMENT,_listenToData loop,key 8209 byteListPrep [17, 32, 0, 0, 255, 255, 0, 0, 126, 254, 0, 12, 92, 34, 0, 0, 6]
2024-03-10 07:16:05.767029,INFO,FITNESS_EQUIPMENT,_listenToData loop,key 8209 byteListPrep [17, 32, 0, 0, 0, 0, 0, 128, 141, 1, 192, 244, 94, 34, 0, 0, 6]
2024-03-10 07:16:06.533624,INFO,FITNESS_EQUIPMENT,_listenToData loop,key 8209 byteListPrep [17, 32, 0, 0, 1, 0, 0, 0, 148, 4, 192, 216, 97, 34, 0, 0, 6]
```

This is the point of `revolutions` overflow.  Byte 6 is not being used for `revolutions`.  So I no longer think there are random bit flips or some error in the bluetooth packets.  Instead, I think `revolutions` is a 2 byte value not a 3 byte value.  I have updated schwinn_x70.dart to reflect this in the cadence mix-in initialization.  BTW, this is how I would have ignored the high 8 bits.

>3. If the revolution time didn't change but the time stamp did, then we need to update the entry in the queue with the newer time stamp. (?) Because the cadence is essentially the deltaRevolutions / deltaTime.

There are three pieces of cadence data:
* time: the time counter in milliseconds as reported by the equipment
* revolutions: the revolutions counter as reported by the equipment
* timeStamp: a timestamp applied by cadence mix-in when the record is created or a duplicated encountered

If neither `time` nor `revolutions` changed, it's OK to update `timeStamp`.  In fact, I think it's always OK to update `timeStamp` because it's not used to calculate RPM.  It's only used to expire entries in the queue.

For a device like the Schwinn x70 that only reports non-fractional revolution counts, the most accurate RPM is calculated when `time` is recorded as closely as possible to the actual time that `revolutions` was incremented.  It is OK to update `timeStamp` for an existing entry in the queue, but I think `time` should only be recorded for the first occurrence of a `revolutions` value.  This PR implements that by only adding to the queue when the new `revolutions` is greater than `last.revolutions`.

**Comment by MrCsabaToth** [comment]
That's a very important discovery. However I haven't heard such complaints from 170 or 270 users. This can be also because I don't necessarily have an extensive user base with those bikes and they might just deal with glitches. I forgot but do you have a Schwinn 470? Before we can apply any such change "globally" for x70 models, we'd need to verify this finding on a 170, 270, and possibly 570u.

Currently I'm applying the x70 proprietary algorithm only based on if the x70's proprietary services UUID and characteristic UUIDs present. Same algorithm for all. If the 170, 270, or 570 behaves differently, then we'd need to differentiate by model names. For that we'd need to see what those bikes return.

An extra solution could be to make this feature switchable by a preferences settings. This way if someone experiences problems they can toggle the switch. This is only necessary if it turns out that any of those bikes behave differently (hopefully not).

**Comment by tkordenbrock** [comment]
I have the Schwinn 270.

Depending on how closely a user watches their cadence history, they may just missed it.  It only shows up for a few seconds at the time of the overflow while the overflow is in the cadence mix-in queue.  It looks like the chart below in Garmin Connect.  And given that the current power algorithm doesn't use cadence, the cadence history is the only place it would show up.

Schwinn270-revs-overflow

> For that we'd need to see what those bikes return.

How do you get that info?  Is there a community of motivated users that are interested in helping with these kinds of problems?

> An extra solution could be to make this feature switchable by a preferences settings.

A preference setting would work for me if there are no other users reporting this problem.  I could also continue to use my own custom builds.  These changes are small enough that I can easily rebase them as `develop` moves.

**Review by MrCsabaToth — APPROVED** [review]

**Comment by MrCsabaToth** [comment]
Contributes to #318
* Identified a byte unnecessarily used as part of the cadence bytes and causing cadence jitters
* Improved cadence mixin logic

**Pull request merged**
